# Generated by Django 2.2.1 on 2019-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gmgallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmgallery',
            name='image',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
    ]
