# Generated by Django 2.2.1 on 2019-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gmgallery', '0003_auto_20190612_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmgallery',
            name='image',
            field=models.ImageField(default='myphoto', upload_to='myphoto/'),
        ),
    ]
