# Generated by Django 2.2.1 on 2019-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gmgallery', '0004_auto_20190612_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmgallery',
            name='image',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
    ]
