# Generated by Django 2.2.1 on 2019-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gmgallery', '0005_auto_20190612_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmgallery',
            name='image',
            field=models.ImageField(height_field='height', upload_to='static/myphoto', width_field='width'),
        ),
    ]
